### PR TITLE
Make it compile with Qt 5.12

### PR DESCRIPTION
**Pull request by z3ntu**

### CODE REVIEW

**Review by zsombi — COMMENTED** [review]
Glad to see this is going forward!
There seems to be a change in the QML parsing backend, as you're getting build error:
ucstylehints_p.h:89:10: error: 'void UCStyleHintsParser::verifyBindings(const QQmlRefPointer<QV4::CompiledData::CompilationUnit>&, const QList<const QV4::CompiledData::Binding*>&)' marked 'override', but does not override
     void verifyBindings(const QQmlRefPointer<QV4::CompiledData::CompilationUnit> &compilationUnit, const QList<const QV4::CompiledData::Binding *> &bindings) override;
          ^~~~~~~~~~~~~~
ucstylehints_p.h:90:10: error: 'void UCStyleHintsParser::applyBindings(QObject*, const QQmlRefPointer<QV4::CompiledData::CompilationUnit>&, const QList<const QV4::CompiledData::Binding*>&)' marked 'override', but does not override
     void applyBindings(QObject *obj, const QQmlRefPointer<QV4::CompiledData::CompilationUnit> &compilationUnit, const QList<const QV4::CompiledData::Binding *> &bindings) override;
          ^~~~~~~~~~~~~

**Comment by z3ntu** [comment]
@zsombi That's because the CI doesn't compile it against Qt 5.12...

**Comment by dobey** [comment]
> @zsombi That's because the CI doesn't compile it against Qt 5.12...

You need to keep the code buildable against 5.9 as well. Please update your changes so it can build against both.

**Comment by z3ntu** [comment]
I don't think this will be possible except either duplicating the file and choosing the one for the build Qt version in the build system or using tons of `#ifdef` macros

**Comment by zsombi** [comment]
> I don't think this will be possible except either duplicating the file and choosing the one for the build Qt version in the build system or using tons of `#ifdef` macros

You can move the differences in separate files and pick the proper ones from the .pro file. Lot cleaner than having a bunch of ifdefs...

**Comment by dobey** [comment]
Or another option could be to simply define the type in the header file with a single #if/#else block as a macro, then use the macro in the code, as this seems to be only changing a single type from a pointer to a templated reference type for the same pointer type.

**Comment by z3ntu** [comment]
@patrickathompson For Qt 5.13 having this additional commit should work: https://github.com/z3ntu/ubuntu-ui-toolkit/commit/ab542b01f461951dd732d8eb1bdb4bf5df4eea6e

**Comment by vanyasem** [comment]
@z3ntu can confirm that this commit makes it compile with Qt5.13

**Comment by dobey** [comment]
This still needs to be fixed to ensure it still compiles against 5.9 as well though.

**Review by dobey — CHANGES_REQUESTED** [review]
Needs to support building against Qt 5.9 still as well.

**Comment by mariogrip** [comment]
Made this: https://github.com/ubports/ubuntu-ui-toolkit/pull/61

@zsombi: If you have time, please review there also :)

**Comment by z3ntu** [comment]
Closing in favor of #61 , many thanks to @mariogrip for pushing this forward!
